---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)s"
  color:
    format: "%(threadName)s - %(name)s - %(levelname)s - %(message)s"
    (): {{cookiecutter.project_pkg}}.logger.ColoredFormatter
    use_color: true

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: color
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /var/log/{{cookiecutter.project_pkg}}/app.log
    maxBytes: 20971520 # 20MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: /var/log/{{cookiecutter.project_pkg}}/error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, info_file_handler, error_file_handler]

